name: Build and deploy to gh-pages

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f docs/requirements.txt ]; then
          pip install -r docs/requirements.txt
        else
          pip install sphinx myst-parser sphinx-rtd-theme
        fi

    - name: Build HTML
      run: |
        python -m sphinx -M html docs/source docs/build -a

    - name: Add PDF to site downloads (if present)
      run: |
        mkdir -p docs/build/html/_downloads
        if [ -f docs/build/latex/MusikkOgBevegelse.pdf ]; then
          cp docs/build/latex/MusikkOgBevegelse.pdf docs/build/html/_downloads/
        fi

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        publish_branch: gh-pages
        keep_history: false
