name: Build and deploy Sphinx site

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        if [ -f docs/requirements.txt ]; then
          pip install -r docs/requirements.txt
        else
          pip install sphinx myst-parser sphinx-rtd-theme sphinxcontrib-plantuml
        fi

    - name: Build HTML
      working-directory: ./
      run: |
        source .venv/bin/activate
        python -m sphinx -M html docs/source docs/build -a

    - name: Build PDF
      working-directory: ./
      env:
        # Allow LaTeX to run; assumes texlive is available on runner (ubuntu-latest usually has TeX Live lite)
        # If missing, the PDF step will fail — see README for local PDF generation instructions.
        PATH: "${{ env.PATH }}"
      run: |
        source .venv/bin/activate
        python -m sphinx -M latexpdf docs/source docs/build -a || true

    - name: Upload PDF artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: musikkogbevegelse-pdf
        path: docs/build/latex/MusikkOgBevegelse.pdf

    - name: Deploy to GitHub Pages
      uses: actions/configure-pages@v4

    - name: Deploy
      id: deploy
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/build/html

    - name: Publish
      uses: actions/deploy-pages@v1
      with: {}
